// This file is auto-generated by the FlutterFire CLI.
// Run `flutterfire configure` in your project root and it will
// REPLACE this placeholder with your real project's options.
//
// Do not hand-edit values here once generated — re-run flutterfire configure instead.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'run `flutterfire configure`.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB36XZh2Ybhd3ThRk2A9boNTJNpDxyuKbw',
    appId: '1:379017038335:ios:67cc8a2a7105af088cbfca',
    messagingSenderId: '379017038335',
    projectId: 'nutriequine-d881d',
    storageBucket: 'nutriequine-d881d.firebasestorage.app',
    iosBundleId: 'com.example.nutriequineApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZyuFFjvvCI5LMUyKeS_ctY2lcfkbFN2A',
    appId: '1:379017038335:android:62f1915e7b888dfa8cbfca',
    messagingSenderId: '379017038335',
    projectId: 'nutriequine-d881d',
    storageBucket: 'nutriequine-d881d.firebasestorage.app',
  );
}
